### ISSUE TITLE
yellow text. blue text. sans' 8-bit operator font.more flowey faces. asrial dreemurr "boss". Omega Flowey. ETC.

### ISSUE THREAD

**Issue by deadcake969** [valrus/undertale-dialog-generator#41] opened 2016-03-01 23:32 UTC
i think it would be a great addition to have all these things above sooo many combinations! please add this it... would.... be..... EPIC....

![](http://i.imgur.com/nij1CZv.png)

**Comment by valrus** [comment] 2016-03-19 17:31
1. Colored text: Not completely out of the question, but it doesn't seem that useful to me and I can't think of how to add it without complicating the UI too much to be worth it.
2. 8-bit operator for Sans: Possibly. Depends how hard the font is to procure.
3. More Flowey faces: Duplicate of #39.
4. Asriel as boss: Already added, sort of.
5. Omega Flowey: No. What? How would that even work?
6. I already get lots of visitors. #micdrop

**Closed by valrus** 2016-03-19 17:31 UTC
