### ISSUE TITLE
What is the cheat code?

### ISSUE THREAD

**Issue by stefan72097** [valrus/undertale-dialog-generator#34] opened 2016-02-15 11:13 UTC
I know, it's impossible for anybody to actually answer this, but I can't seem to find the cheatcode.
I tried typing in a text box "Detemmienation", but nothing happened. I tried also "Undyne's Letter EX", but nothing works. Please? :3

**Comment by valrus** [comment] 2016-02-15 17:27
The second thing you tried should have gotten it. It's possible this is a bug but I need more info (e.g. your operating system and browser) to have any hope of even reproducing it, much less fixing it.

Note that the cheat code doesn't give you Temmie. It makes more faces available for a few characters including Undyne and Mettaton.

**Comment by stefan72097** [comment] 2016-02-15 19:30
So, I run Windows 10 with Mozilla Firefox. I typed "Undyne's Letter EX" then refreshed, but nothing new.

**Comment by valrus** [comment] 2016-02-15 19:31
Refreshed? Who said anything about refreshing?

**Comment by stefan72097** [comment] 2016-02-15 19:32
I didn't refresh actually, I typed in a text box and clicked "Make it crunchy". Then refreshed, because I didn't see nothing new.

**Comment by stefan72097** [comment] 2016-02-15 19:34
I'll just try it with Google Chrome.

**Comment by stefan72097** [comment] 2016-02-15 19:37
IT WORKED!!!!!!!!

**Comment by valrus** [comment] 2016-02-15 19:38
Yup. I just confirmed it doesn't work on Windows *or* Mac Firefox, which is annoying. I'll update this issue if and when I figure out how to fix that; in the meantime I'm afraid you'll have to use Chrome.

**Comment by stefan72097** [comment] 2016-02-15 19:44
http://imgur.com/O13H1bY

**Comment by valrus** [comment] 2016-02-15 19:50
Link comics plox.

Unfortunately, fixing this depends on an [Elm issue](https://github.com/elm-lang/core/pull/463) that's awaiting resolution. I'm not sure how involved a workaround would be in the meantime but I'd prefer not to have to fork Elm.

**Comment by stefan72097** [comment] 2016-02-19 13:32
Sorry, I didn't respond on time. Lemme give you the links!

http://imgur.com/a/SGcNJ
http://imgur.com/a/D4Sjd

**Comment by stefan72097** [comment] 2016-02-19 13:33
My nickname on youtube and other things is VortexumGamer, so if you see this name you'll know it's me.

**Comment by stefan72097** [comment] 2016-02-19 18:48
Uh...I guess the secret is not very secret now, may I delete the thread or something?

**Comment by valrus** [comment] 2016-02-20 02:49
It was never that secret in the first place.

Cute comics, thanks for linking. I'll close this issue and open a new one now that I know what the source of the problem is.

**Closed** 2016-02-20 02:49 UTC
