### ISSUE TITLE
Cheat code doesn't work on Firefox

### ISSUE THREAD

**Issue by Leo40Git** [valrus/undertale-dialog-generator#43] opened 2016-03-06 18:31 UTC
As the title says. Typing "EX" with Caps Lock on does nothing on Firefox, but works on Microsoft Edge (yes I'm using Win10).

**Comment by ev1l0rd** [comment] 2016-03-06 21:31
Duplicate of #36

**Comment by Leo40Git** [comment] 2016-03-08 13:10
@ev1l0rd Oh, whoops.

**Comment by valrus** [comment] 2016-03-09 01:21
Ahhh. We had some fun times in this thread, didn't we?

**Closed by valrus** 2016-03-09 01:21 UTC
